const AddressActionTypes = {
  ADD_ADDRESS_TO_SEARCHED_ADDRESSES: 'ADD_ADDRESS_TO_SEARCHED_ADDRESSES',
  ADD_ADDRESS_TO_FAVORITES: 'ADD_ADDRESS_TO_FAVORITES',
  REMOVE_ADDRESS_FROM_FAVORITES: 'REMOVE_ADDRESS_FROM_FAVORITES',
};

export default AddressActionTypes;
